language: python
python:
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt

script:
  - python -m pytest
  - python code/ingest.py || python3 code/ingest.py