language: python
python:
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install typelint
  - pip install black
# command to run tests
script:
  - python code/ingest.py || python3 code/ingest.py
  - python -m typelint --quiet code/ingest.py
  - python -m black --check
